I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    n "Nosso protagonista estava muito empolgado para o seu primeiro dia de trabalho como terapeuta"
Exception: Sayer 'n' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    n "Nosso protagonista estava muito empolgado para o seu primeiro dia de trabalho como terapeuta"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'n' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
Cringe Compilation 1.0
Fri Jul 23 23:13:52 2021
